# Conclusion

After conducting a detailed analysis on the dataset, we actually acquire lots of useful information. To be specific, by investigating the occurring time of the crime cases, we observe that most crime cases concentrated at the late evening and afternoon. The number of crime cases increased significantly from 15pm to 22pm, and decreased rapidly in the morning. This finding can be quite helpful when we are scheduling our trips. So in order to decrease the chances of encountering dangers, we should arrange our main events in the morning and early afternoon, 8am to 14pm. Secondly, by analyzing the age distribution of the victims, we can conclude that most victims are between 18-40. Compared with elders, these people have much longer time of staying outside, which increases the probability of exposing to dangers. Hence, people between 18-40 should be more alerted when they are travelling. Third, we also visualize the number of cases in a spatial map. From the graph, we can observe that most cases cluster at the central area of LA, while some other cases concentrate in the northwestern part of LA. This provides valuable information about how we should plan our routes during the travel. Specifically, we should try to avoid the central and northwestern part of LA to reduce the chances of encountering dangers. And if we zoom in the central area, we can discover that crime cases are the most frequent in Hollywood and Fashion District. Hence, we should avoid these two areas during the trip. In conclusion, by conducting a series of exploratory analysis, we extract valuable information about how we should schedule our trips, like location, time, or contents.

Even though we have extracted some useful information from the dataset, there actually exist several limitations during the analysis. First of all, in some columns like Crime Code or weapon description, they contains lots of missing values. For example, in weapon description, about 50% of the data are missing. This will affect the accuracy of our graph and conclusion, because we cannot be sure about why a category is more frequent than the other. It could be that another category is more frequent but main part of its data are missing. Therefore, missing data may provide us misleading information. Moreover, another limitation is that the dataset is transcribed from the crime reports that are typed on paper. Thus, since there are about 2000k lines of data and each line contains 28 columns, there will surely exist some typos, which creates inaccuracies in our analysis. Lastly, for the spatial graphs, we also have some limitations in displaying information. To be specific, due to the size of the figure, in order to ensure the readability of the graph, we cannot display all of the information but only part of the general patterns.

From this project, we can learn some useful lessons. Firstly, we have more understanding about how to process numerical and categorical columns. To be specific, for numeric columns, we cannot directly visualize them in graph because there are too many numeric values, which will make the axis messy. In this case, we should categorize the values into groups, which will make our graph very clean. And by doing series of experiments, we need to pick the best cut for these values. Moreover, different numeric columns will have significantly different scales, some of them ranges between 1-10 while the others ranges between 1-10000. And plotting them directly will distort our graph. Hence, we should standardize them before the visualization. For categorical columns, we should be careful about the types of graph we visualize. Parallel coordinates plot or boxplot are not very suitable for discrete data. In this case, we should try to use mosaic plot or bar charts. Specifically, mosaic plots can be used to show the proportion relationship and bar charts are pretty effective in displaying the frequency. Moreover, another lesson that we learned is how to deal with overplotting. Overplotting means there are too many datapoints in the graph, which causes some of them to overlap. In our graph, there are about 2000k lines of data, so there are lots of overplotting. In this case, we can either try to use the log scale or sample only part of the total data to reduce the number of datapoints on the graph. In conclusion, this project not only allows us learn how to process numeric and categorical features, but also provides insights about how to solve overplotting problems.

For the future, I would suggest to collect more kinds of criminal information. In this dataset, it includes information like victim sex, age, race, occurring time, location, weapon used, etc. However, it lacks the information of the criminals like their age and sex. These information are very important and useful because after having a deeper understanding about criminals, we can know how to avoid them. Hence, if we have more time, we would collect more information about these aspects, which will make our results more comprehensive and convincing. In conclusion, this project really opens the possibilities for the future research and study.
