--- 
title: "EDAV-F22-final-project"
author: "FeiFan Li, Wenqi Sun, Yusong Zhao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Nowadays, what is the toppest concern when we travel to a foreign city, and most people will say safety. If the basic safety cannot be guaranteed, we cannot enjoy the trip. Thus, what are the effective ways to ensure our own safety? To be specific, when we schedule the routes, we can avoid the areas that have high crime frequency. Also, since most crimes are occurred during the night, we can arrange all our activities during the daytime to reduce the possibilities of encountering dangers. Or we can avoid leaving valuable items in the vehicles. All these strategies are built on our understanding of crimes in that city. Therefore, how can we gain a comprehensive understanding of the criminal information in the city? One straightforward way is to investigate the dataset that contains specific details about all incidents of crimes.

For this project, we mainly want to study the crimes occurred in Los Angeles. In this case, we found a dataset from the Los Angeles Open Data, which contains crime reports from 2020 to present. This dataset includes over 550k rows of data and 28 columns, which provides us sufficient amount of data for data analysis and data visualization. Specifically, the columns contain very specific information about crime, such as crime location, occurring time, victim description, or weapon status, etc. Hence, analyzing these columns will allow us to discover some patterns behind crimes like where they usually happen or in what kind of scenarios.

For this project, we will use R for the data analysis and related visualization. As we know, R is a powerful language for data processing and statistical calculation, which is compatible with our goal. The project consists of 6 main parts: introduction, proposal, data, results, interactive component, and conclusion. In the proposal, we will briefly introduce the topic and list the conditions of our dataset. In the data section, we will give detailed information about the dataset and start to do data preprocessing like fill in missing value or process outliers. In the results and interactive component part, we will show the data analysis and what patterns we observe. Lastly, the conclusion part will summarize our findings and what we learn from this project.